version: '3.8'
services:
  weather-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - NEXT_PUBLIC_INTERNAL_API_KEY=${NEXT_PUBLIC_INTERNAL_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
